# Generated by Django 4.2.7 on 2023-11-02 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='categories',
            field=models.ManyToManyField(to='events.category'),
        ),
        migrations.DeleteModel(
            name='EventCategory',
        ),
    ]
