# Generated by Django 4.2.6 on 2023-10-22 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_category_comment_event_eventcategory_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Response',
            new_name='RegistrationResponse',
        ),
    ]
