# Generated by Django 4.2.7 on 2023-11-03 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_categories_delete_eventcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventregistration',
            name='response',
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='is_registered',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='RegistrationResponse',
        ),
    ]
