# Generated by Django 4.2.6 on 2023-10-24 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('events', '0004_comment_created_at_comment_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.appuser'),
        ),
        migrations.AlterField(
            model_name='event',
            name='organizer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.appuser'),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.appuser'),
        ),
    ]
