# Generated by Django 4.2.6 on 2023-10-31 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_comment_user_id_alter_event_organizer_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='organizer_id',
            new_name='user_id',
        ),
    ]
